/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  settings/seo.ts  —  Central SEO configuration for Jay Patel's portfolio
 * ─────────────────────────────────────────────────────────────────────────────
 *
 *  Everything SEO lives here:
 *    • Site-wide metadata (title, description, keywords, canonical)
 *    • Open Graph (Facebook / LinkedIn / WhatsApp share cards)
 *    • Twitter / X cards
 *    • Robots directives
 *    • JSON-LD structured data:
 *        – Person schema          (who Jay is)
 *        – WebSite schema         (site identity — no fake SearchAction)
 *        – ProfilePage schema     (portfolio page)
 *        – BreadcrumbList schema  (resume page)
 *        – FAQ schema             (only when showFAQ is true)
 *    • Per-page metadata helpers  (resumePageMetadata)
 *
 *  Usage in app/layout.tsx:
 *    import { rootMetadata, rootViewport } from "@/settings/seo";
 *    export const metadata = rootMetadata;
 *    export const viewport  = rootViewport;
 *
 *  Usage in any route's page.tsx:
 *    import { resumePageMetadata } from "@/settings/seo";
 *    export const metadata = resumePageMetadata;
 *
 *  To add JSON-LD to a page:
 *    import { personJsonLd, faqJsonLd } from "@/settings/seo";
 *    <script type="application/ld+json"
 *            dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }} />
 * ─────────────────────────────────────────────────────────────────────────────
 */

import type { Metadata, Viewport } from "next";
import { siteConfig } from "@/settings";
// ─── Base URL ──────────────────────────────────────────────────────────────────
// Canonical / OG / sitemap must be the public domain — never VERCEL_URL.
// VERCEL_URL is a unique deploy host (e.g. jay-portfolio-xxxx.vercel.app).
const PRODUCTION_ORIGIN = "https://jaypateldev.com";

export const BASE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.NODE_ENV === "production" ? PRODUCTION_ORIGIN : "http://localhost:3000")
).replace(/\/$/, "");

/** Homepage canonical — always with a trailing slash (`https://jaypateldev.com/`). */
export const HOME_URL = `${BASE_URL}/`;

/** Real content date — do not use `new Date()` in JSON-LD or sitemap. */
export const LAST_UPDATED = "2026-08-17";

// ─── Core copy ─────────────────────────────────────────────────────────────────
// Change these to adjust the text that appears in Google results and link previews.

export const SEO_TITLE_TEMPLATE = `%s | ${siteConfig.fullName}`;
export const SEO_TITLE_DEFAULT = `${siteConfig.fullName} — Full Stack Developer`;

export const SEO_DESCRIPTION =
  `${siteConfig.fullName} is a Full Stack Developer based in ${siteConfig.location} ` +
  `specialising in React, Next.js, Node.js and the MERN stack. ` +
  `Building performant, scalable web applications with 3.5+ years of professional experience.`;

// ─── Keywords ──────────────────────────────────────────────────────────────────
// These feed the <meta name="keywords"> tag and help contextualise the page for
// crawlers even though Google no longer ranks on keywords alone.
export const SEO_KEYWORDS: string[] = [
  // Identity
  siteConfig.fullName,
  "Jay Patel",
  "Jay Patel developer",
  "Jay Patel portfolio",
  "Jay Patel Full Stack Developer",
  "Jay Patel MERN developer",

  // Role
  "Full Stack Developer",
  "MERN Stack Developer",
  "React Developer",
  "Next.js Developer",
  "Node.js Developer",
  "TypeScript Developer",
  "Web Developer",
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",

  // Location
  "Full Stack Developer Ahmedabad",
  "Web Developer India",
  "React Developer India",
  "Ahmedabad developer",
  "Krishang Technolab developer",

  // Tech Stack
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Express.js",
  "MongoDB",
  "PostgreSQL",
  "Tailwind CSS",
  "Redux",
  "Zustand",
  "GraphQL",
  "REST API",
  "Docker",
  "AWS",
  "CI/CD",
  "Git",
  "Figma",

  // General
  "developer portfolio",
  "hire developer",
  "freelance developer",
  "open to work",
  "web application development",
  "scalable web apps",
  "MERN stack",
];

// ─── Open Graph image ──────────────────────────────────────────────────────────
// Generated by app/opengraph-image.tsx (1200×630). Also used on /resume cards.
export const OG_IMAGE = {
  url: "/opengraph-image",
  width: 1200,
  height: 630,
  alt: `${siteConfig.fullName} — Full Stack Developer Portfolio`,
  type: "image/png",
} as const;

// ─── Twitter handle ────────────────────────────────────────────────────────────
// Update this if Jay has a Twitter / X account, otherwise keep it undefined.
export const TWITTER_HANDLE: string | undefined = undefined;

// ─────────────────────────────────────────────────────────────────────────────
//  Root Metadata  (used in app/layout.tsx)
// ─────────────────────────────────────────────────────────────────────────────
export const rootMetadata: Metadata = {
  // ── Basic ──────────────────────────────────────────────────────────────────
  metadataBase: new URL(BASE_URL),

  title: {
    default: SEO_TITLE_DEFAULT,
    template: SEO_TITLE_TEMPLATE,
  },

  description: SEO_DESCRIPTION,
  keywords: SEO_KEYWORDS,

  authors: [
    {
      name: siteConfig.fullName,
      url: siteConfig.github,
    },
  ],

  creator: siteConfig.fullName,
  publisher: siteConfig.fullName,

  // ── Robots ─────────────────────────────────────────────────────────────────
  // Controlled by siteConfig.allowIndexing.
  // Set allowIndexing: false in settings/features.ts (allowIndexing) / settings/ to block all crawlers
  // (useful while the site is still in development / staging).
  // Flip it to true when you go live on your real domain.
  robots: siteConfig.allowIndexing
    ? {
        index: true,
        follow: true,
        googleBot: {
          index: true,
          follow: true,
          "max-video-preview": -1,
          "max-image-preview": "large" as const,
          "max-snippet": -1,
        },
      }
    : {
        index: false,
        follow: false,
        nocache: true,
        googleBot: {
          index: false,
          follow: false,
          noimageindex: true,
        },
      },

  // ── Canonical / Alternates ─────────────────────────────────────────────────
  alternates: {
    canonical: HOME_URL,
  },

  // ── Open Graph ─────────────────────────────────────────────────────────────
  openGraph: {
    type: "profile",
    locale: "en_US",
    url: HOME_URL,
    siteName: `${siteConfig.fullName} — Portfolio`,
    title: SEO_TITLE_DEFAULT,
    description: SEO_DESCRIPTION,
    images: [OG_IMAGE],
    // Profile-specific OG fields
    firstName: "Jay",
    lastName: "Patel",
    username: siteConfig.githubUsername,
    gender: "male",
  },

  // ── Twitter / X ────────────────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: SEO_TITLE_DEFAULT,
    description: SEO_DESCRIPTION,
    images: [OG_IMAGE.url],
    // Uncomment and set TWITTER_HANDLE (e.g. "@jaypatel_dev") to populate these:
    // site: TWITTER_HANDLE,
    // creator: TWITTER_HANDLE,
  },

  // ── App ────────────────────────────────────────────────────────────────────
  applicationName: `${siteConfig.fullName} Portfolio`,
  category: "technology",
  classification: "Portfolio, Developer, Software Engineer",

  // ── Verification ──────────────────────────────────────────────────────────
  // Next.js renders this as <meta name="google-site-verification" content="…" />.
  // Override with NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION if Search Console issues a new token.
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION || undefined,
    ...(process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION
      ? { other: { "msvalidate.01": process.env.NEXT_PUBLIC_BING_SITE_VERIFICATION } }
      : {}),
  },

  // ── Icons ──────────────────────────────────────────────────────────────────
  // Generated by app/icon.tsx and app/apple-icon.tsx
  icons: {
    icon: [{ url: "/icon", type: "image/png" }],
    apple: "/apple-icon",
  },
};

// ─────────────────────────────────────────────────────────────────────────────
//  Root Viewport  (kept separate from Metadata per Next.js 15 requirement)
// ─────────────────────────────────────────────────────────────────────────────
export const rootViewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafaf8" },
    { media: "(prefers-color-scheme: dark)", color: "#0e0f17" },
  ],
};

// ─────────────────────────────────────────────────────────────────────────────
//  Per-page metadata helpers
// ─────────────────────────────────────────────────────────────────────────────

export const resumePageMetadata: Metadata = {
  title: `Resume | ${siteConfig.fullName}`,
  description:
    `View ${siteConfig.fullName}'s full resume — ` +
    `Full Stack Developer with 3+ years experience in React, Next.js, Node.js, ` +
    `MongoDB, and TypeScript. Based in ${siteConfig.location}.`,
  keywords: [
    `${siteConfig.fullName} resume`,
    `${siteConfig.fullName} CV`,
    "Full Stack Developer resume",
    "MERN developer resume",
    "React developer CV",
    ...SEO_KEYWORDS.slice(0, 20),
  ],
  alternates: {
    canonical: `${BASE_URL}/resume`,
  },
  openGraph: {
    type: "profile",
    url: `${BASE_URL}/resume`,
    title: `${siteConfig.fullName} — Resume`,
    description:
      `Full Stack Developer resume — React, Next.js, Node.js, TypeScript, MongoDB. ` +
      `3+ years of experience. Based in ${siteConfig.location}.`,
    images: [OG_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: `${siteConfig.fullName} — Resume`,
    description: `Full Stack Developer resume — MERN stack, 3+ years experience. ${siteConfig.location}.`,
    images: [OG_IMAGE.url],
  },
  // Resume pages are sometimes excluded from indexing — remove the line below
  // if you want Google to index the /resume route.
  robots: {
    index: true,
    follow: true,
  },
};

export const engineeringPageMetadata: Metadata = {
  title: `Engineering | ${siteConfig.fullName}`,
  description: `How ${siteConfig.fullName}'s portfolio is built: App Router, APIs, rate limits, CSP, CI, and settings as source of truth.`,
  alternates: { canonical: `${BASE_URL}/engineering` },
  openGraph: {
    url: `${BASE_URL}/engineering`,
    title: `${siteConfig.fullName} — Engineering`,
    description: "How this portfolio is built and operated.",
    images: [OG_IMAGE],
  },
};

export function projectPageMetadata(project: {
  slug: string;
  title: string;
  tagline: string;
  desc: string;
}): Metadata {
  return {
    title: `${project.title} | ${siteConfig.fullName}`,
    description: project.desc.slice(0, 160),
    alternates: { canonical: `${BASE_URL}/projects/${project.slug}` },
    openGraph: {
      url: `${BASE_URL}/projects/${project.slug}`,
      title: `${project.title} — ${project.tagline}`,
      description: project.desc.slice(0, 160),
      images: [OG_IMAGE],
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
//  JSON-LD Structured Data
//  Paste these as <script type="application/ld+json"> in your page components.
//  All schemas are validated against schema.org.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Person schema — tells Google who Jay is.
 * Shows in Knowledge Panel and rich results.
 */
export const personJsonLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  "@id": `${BASE_URL}/#person`,
  name: siteConfig.fullName,
  givenName: "Jay",
  familyName: "Patel",
  url: HOME_URL,
  image: `${BASE_URL}/opengraph-image`,
  email: `mailto:${siteConfig.email}`,
  jobTitle: "Full Stack Developer",
  description: SEO_DESCRIPTION,
  address: {
    "@type": "PostalAddress",
    addressLocality: "Ahmedabad",
    addressCountry: "IN",
  },
  sameAs: [siteConfig.github, siteConfig.linkedin],
  knowsAbout: [
    "React",
    "Next.js",
    "TypeScript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "REST APIs",
    "GraphQL",
    "Tailwind CSS",
    "Docker",
    "AWS",
    "Full Stack Development",
    "MERN Stack",
    "Web Application Development",
  ],
  alumniOf: [
    {
      "@type": "CollegeOrUniversity",
      name: "SCET, Kalol",
      sameAs: "https://www.swaminarayanuniversity.ac.in",
    },
    {
      "@type": "CollegeOrUniversity",
      name: "GPG, Gandhinagar",
    },
  ],
  worksFor: {
    "@type": "Organization",
    name: "Krishang Technolab",
    url: "https://www.krishangtechnolab.com",
    address: {
      "@type": "PostalAddress",
      addressLocality: "Ahmedabad",
      addressCountry: "IN",
    },
  },
};

/**
 * WebSite schema — site identity only.
 * Do not add SearchAction: this site has no search results URL.
 */
export const webSiteJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebSite",
  "@id": `${BASE_URL}/#website`,
  name: `${siteConfig.fullName} — Portfolio`,
  url: HOME_URL,
  description: SEO_DESCRIPTION,
  author: {
    "@id": `${BASE_URL}/#person`,
  },
  inLanguage: "en-US",
};

/**
 * ProfilePage schema — marks this as a personal portfolio / profile page.
 */
export const profilePageJsonLd = {
  "@context": "https://schema.org",
  "@type": "ProfilePage",
  "@id": `${BASE_URL}/#profilepage`,
  url: HOME_URL,
  name: SEO_TITLE_DEFAULT,
  description: SEO_DESCRIPTION,
  breadcrumb: {
    "@type": "BreadcrumbList",
    itemListElement: [
      {
        "@type": "ListItem",
        position: 1,
        name: "Home",
        item: HOME_URL,
      },
    ],
  },
  mainEntity: {
    "@id": `${BASE_URL}/#person`,
  },
  about: {
    "@id": `${BASE_URL}/#person`,
  },
  dateModified: LAST_UPDATED,
};

/**
 * Resume / CV BreadcrumbList schema.
 */
export const resumeBreadcrumbJsonLd = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "@id": `${BASE_URL}/resume#breadcrumb`,
  itemListElement: [
    {
      "@type": "ListItem",
      position: 1,
      name: "Home",
      item: HOME_URL,
    },
    {
      "@type": "ListItem",
      position: 2,
      name: "Resume",
      item: `${BASE_URL}/resume`,
    },
  ],
};

/**
 * FAQ structured data — generated from siteConfig.faqItems.
 * Only injected when showFAQ is true (markup must match visible content).
 */
export const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "@id": `${BASE_URL}/#faq`,
  mainEntity: siteConfig.faqItems.map((item) => ({
    "@type": "Question",
    name: item.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: item.answer,
    },
  })),
};

/**
 * Convenience array — all JSON-LD schemas for the home page.
 * Spread this into your page to inject all schemas at once.
 */
export const homePageJsonLdSchemas = [
  personJsonLd,
  webSiteJsonLd,
  profilePageJsonLd,
  ...(siteConfig.showFAQ ? [faqJsonLd] : []),
];
